name: Generate HTML from Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc jq

    - name: Convert Markdown to HTML and Generate JSON
      run: |
        mkdir -p data/announcements
        echo '{ "announcements": [' > data/announcements.json
        first=true
        for file in data/markdown/*.md; do
          base=$(basename "$file" .md)
          date=$(head -n 1 "$file")
          title=$(head -n 2 "$file" | tail -n 1 | sed 's/^# //')
          pandoc --standalone --mathjax --metadata title="$title" "$file" -o "data/announcements/$base.html"
          if [ "$first" = true ]; then
            first=false
          else
            echo ',' >> data/announcements.json
          fi
          echo "{ \"title\": \"$title\", \"date\": \"$date\", \"file\": \"data/announcements/$base.html\" }" >> data/announcements.json
        done
        echo '] }' >> data/announcements.json

    - name: Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/announcements/*.html data/announcements.json
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Convert Markdown to HTML and update announcements.json"
          git push
        else
          echo "No changes to commit"
