name: Convert TextBundle to HTML

on:
  push:
    branches:
      - main   # 监听 main 分支
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Convert TextBundle to HTML
      run: |
        python scripts/main.py

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/notices/*/index.html data/notices.json
        git rm --cached $(git ls-files --deleted data/notices/*/index.html) || true
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automatically convert TextBundle to HTML and update JSON"
          git push
        else
          echo "No changes to commit"
