name: Convert TextBundle to HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Convert TextBundle to HTML
      working-directory: ./scripts
      run: |
        python main.py

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/notices/**/*.html data/notices.json || true
        git ls-files --deleted | xargs -r git rm || true
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automatically convert TextBundle to HTML and update JSON"
          git push
        else
          echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
