name: Update Notice JSON

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 每天 0:00 运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate Notice JSON
      run: |
        python scripts/generate_notice_json.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/notice.json
        git commit -m "Update notice.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}